# Generated by Django 5.2.7 on 2025-10-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
