# Generated by Django 5.2.7 on 2025-10-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure Project'), ('renovation', 'Building Renovation'), ('equipment', 'Equipment Purchase'), ('other_project', 'Other Project'), ('official_allowance', 'Official Allowance'), ('travel_allowance', 'Travel Allowance'), ('meal_allowance', 'Meal Allowance'), ('other_allowance', 'Other Allowance'), ('electricity', 'Electricity Bill'), ('water', 'Water Bill'), ('internet', 'Internet Bill'), ('other_utility', 'Other Utility'), ('building_maintenance', 'Building Maintenance'), ('equipment_maintenance', 'Equipment Maintenance'), ('vehicle_maintenance', 'Vehicle Maintenance'), ('other_maintenance', 'Other Maintenance'), ('stationery', 'Stationery'), ('printing', 'Printing Materials'), ('cleaning', 'Cleaning Supplies'), ('other_supplies', 'Other Supplies'), ('emergency', 'Emergency Expense'), ('miscellaneous', 'Miscellaneous')], max_length=30),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.CharField(choices=[('barangay_clearance', 'Barangay Clearance'), ('indigency', 'Certificate of Indigency'), ('residency', 'Certificate of Residency'), ('good_moral', 'Good Moral Character'), ('other_cert', 'Other Certificate'), ('business_permit', 'Business Permit'), ('construction_permit', 'Construction Permit'), ('event_permit', 'Event Permit'), ('other_permit', 'Other Permit'), ('community_donation', 'Community Donation'), ('religious_donation', 'Religious Donation'), ('charity_donation', 'Charity Donation'), ('other_donation', 'Other Donation'), ('infrastructure_grant', 'Infrastructure Grant'), ('health_grant', 'Health Program Grant'), ('education_grant', 'Education Grant'), ('other_grant', 'Other Grant'), ('rental_income', 'Rental Income'), ('interest_income', 'Interest Income'), ('miscellaneous', 'Miscellaneous')], max_length=30),
        ),
    ]
