# Generated by Django 5.2.7 on 2025-10-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
    ]
