# Generated by Django 5.2.7 on 2025-10-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_complaint_complaintattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'Incident/Complaint', 'verbose_name_plural': 'Incidents/Complaints'},
        ),
        migrations.AddField(
            model_name='complaint',
            name='incident_type',
            field=models.CharField(choices=[('disturbance', 'Disturbance'), ('missing_item', 'Missing Item'), ('accident', 'Accident'), ('property_damage', 'Property Damage'), ('noise_complaint', 'Noise Complaint'), ('health_concern', 'Health Concern'), ('sanitation', 'Sanitation Issue'), ('streetlight', 'Streetlight/Infrastructure'), ('stray_animals', 'Stray Animals'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='received', max_length=20),
        ),
    ]
