# Generated by Django 5.2.7 on 2025-10-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_alter_complaint_options_complaint_incident_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
